
server:
  port: 8080

spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1s
        max-idle: 10
        min-idle: 0
    timeout: 1000ms

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      uri: mongodb://localhost:27017/mongodb_test


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.mybatisdemo.entity
  configuration:
    map-underscore-to-camel-case: true



